In [ ]:
#| default_exp utils.asian_1x2_pnl

In [ ]:
#| hide

from IPython.core.debugger import set_trace

%load_ext autoreload
%autoreload 2

# 1X2 and Asian Handicap Profit
> Profit for 1X2 and Asian handicap betting

In [ ]:
#| export

import mongoengine
import numpy as np
import pandas as pd

Using the `config.toml` credentials included in the main repository, we must first load games data stored in our MongoDb Cluster before testing our betting environment.

In [ ]:
from fastbet.config.localconfig import CONFIG,DB_HOSTS
from fastbet.datastructure.data_extractor import *

In [ ]:
fixture = data_aggregator(
    db_hosts=DB_HOSTS,
    config=CONFIG,
    db_host="public_atlas",
    limit=5,
)
fixture.head()

gameId  game_optaId  \
0  219ef70c0e8a803ec1efdb793443edfaa32398690c7829...       991003   
1  174dba7291174b4dbbfa9ea12dd944bb45bdd8ed905524...       990997   
2  0655e244d8d596b5572e86426e2a7ca6178044efa59437...       991013   
3  019c223b4a03917c2f1685beab4d5d278f7bff3913f239...       991018   
4  0f9ad12eec9f24277ab491f5f26f610eaa918903a34147...       991014   

              gameDate                                         homeTeamId  \
0  2018-08-22 18:45:00  aeb2f56fcedbcf4cd5c780179766996c7bf0b308064541...   
1  2018-08-22 18:45:00  126905d14981e6b97912ad4fec354035ccef26cb8ec4e1...   
2  2018-08-25 14:00:00  9ee012a80cade2df55b71580bf5e238bcd6be6f696fdc1...   
3  2018-08-25 14:00:00  eb89c068ca204a72408360450847a990c97c5b5ff0ec9f...   
4  2018-08-25 16:30:00  04c71986b6503ba5b09a7098ceb79954d20049f21ba45b...   

   homeTeam_optaId                                         awayTeamId  \
0                5  f8daf96ad35eebf1c0a5886c72734ba7dec366d6637052...   
1                7  419088133137a53bfdb1b7e2e682d223d33a6fa075bbfe...   
2               45  38ca605bcd29a5a37697ca66e533ae817ced71b6bf275c...   
3              110  bbb63e4ea54b0d60b48a1f8440254d7e656dfbfcbef825...   
4               17  95d3bddc19a15d34a7876dcffc1a3e9bc63d809b69308a...   

   awayTeam_optaId  tgt_gd  tgt_outcome  preGameOdds1  ...  \
0              108       0          1.0         1.980  ...   
1               94       0          1.0         2.620  ...   
2                2      -3          2.0         2.620  ...   
3               88       2          0.0         1.917  ...   
4               41       0          1.0         2.040  ...   

                                   homeTeamLineupIds  \
0  [156685, 15398, 154561, 165183, 61602, 167802,...   
1  [12150, 59115, 122806, 54764, 49773, 37339, 43...   
2  [52980, 84384, 108799, 83428, 57127, 87396, 20...   
3  [85352, 3773, 105666, 91972, 40555, 61858, 394...   
4  [199796, 56827, 130593, 113564, 16045, 83427, ...   

                   homeTeamLineupSlots  homeTeamFormation  \
0  [11, 9, 1, 3, 4, 5, 6, 2, 10, 8, 7]            4-2-3-1   
1  [4, 6, 8, 9, 11, 7, 5, 2, 3, 1, 10]            4-4-1-1   
2  [2, 6, 8, 5, 7, 10, 1, 11, 3, 9, 4]            4-2-3-1   
3  [6, 9, 1, 10, 4, 7, 3, 11, 2, 5, 8]            4-4-1-1   
4  [7, 1, 5, 2, 8, 3, 4, 10, 9, 6, 11]            4-2-3-1   

   home_team_lineup_received_at     awayTeamName  \
0           2018-08-22 18:15:00          Reading   
1           2018-08-22 18:15:00        Brentford   
2           2018-08-25 13:30:00     Leeds United   
3           2018-08-25 13:30:00        Hull City   
4           2018-08-25 16:00:00  Birmingham City   

                                      awayTeamLineup  \
0  {"Leandro Bacuna": "DMR", "Andy Yiadom": "DR",...   
1  {"Daniel Bentley": "GK", "Ezri Konsa": "DCR", ...   
2  {"Mateusz Klich": "MCR", "Luke Ayling": "DR", ...   
3  {"Eric Lichaj": "DR", "Jordy De Wijs": "DCL", ...   
4  {"Kristian Pedersen": "DL", "Maxime Colin": "D...   

                                   awayTeamLineupIds  \
0  [74297, 87408, 154133, 86857, 17506, 112133, 2...   
1  [79602, 199798, 115382, 114275, 176442, 223911...   
2  [72222, 66588, 98760, 155405, 220037, 61810, 8...   
3  [45139, 173549, 15144, 82771, 240499, 28541, 5...   
4  [229009, 86132, 77800, 114054, 69842, 85365, 8...   

                   awayTeamLineupSlots awayTeamFormation  \
0  [4, 2, 8, 6, 5, 3, 1, 7, 10, 11, 9]             4-4-2   
1  [1, 5, 9, 8, 3, 6, 7, 10, 4, 11, 2]           4-2-3-1   
2  [8, 2, 9, 4, 1, 5, 10, 7, 3, 11, 6]           4-1-4-1   
3  [2, 6, 1, 4, 8, 9, 10, 3, 7, 11, 5]           4-4-1-1   
4  [3, 2, 4, 9, 11, 8, 7, 1, 5, 6, 10]             4-4-2   

  away_team_lineup_received_at  
0          2018-08-22 18:15:00  
1          2018-08-22 18:15:00  
2          2018-08-25 13:30:00  
3          2018-08-25 13:30:00  
4          2018-08-25 16:00:00  

[5 rows x 27 columns]

## Popular betting markets

There are many types of bets available in football today but betting on the match outcome, known as the `1x2` market, is the most popular one by far. The punter can bet the 3 possible match outcomes: *Home-win*, *draw* or *away-win*. 

A second popular market, in particular in Asia, is known as Asian handicap and is directly linked to the game goal difference. It offers only 2 betting options known as *home* (1) or *away* (2) and assumes that one of the team will start with a handicap (known as the line) and the other with an advantage. There are 3 types of Asian handicap markets:

  - *Integer Lines*: if the handicap chosen is equal to the score difference, it can result in a bet being returned.
  - *Half Lines*: the outcome of the wager is either a win or a loss.
  - *Quarter Lines*: Divide your wager equally between the two AH lines above and beyond. For instance, a handicap of -0.75 is really two handicaps for the price of one, with half of your bet being made at -0.5 and the other half at -1, both of which are given the same odds. In this case, we have a win, half-win, half-loss, or a loss.

## PnL computation

### 1X2 market

The PnL of the 1x2 market depends on the match outcome (home-win/draw/away-win) and is *binary*: the punter can either make a profit and get his stake returned or loose his stake.

$$ profit_{1X2} =  Stake *(Odds \times -1)$$
With:

+ Stake : Invested money
+ Odds : 1X2 European/decimal betting odds (> 1)

In [ ]:
#| export


def pnl_1X2(
    selection: np.ndarray,  # The amount invested on each selection.
    outcome: np.ndarray,  # Game result (Binary side outcome), shape=(1,5).
    odds: np.ndarray,  # odds for the current game, shape=(1,5)
) -> np.ndarray:  # 1X2 PnL
    "Returns the 1X2 PnL."
    assert selection.shape == odds.shape, "odds and selection should be same shape!"
    assert outcome.shape == odds.shape, "odds and outcome should be same shape!"
    n = selection.shape[0]

    pnl = selection[:, :3] * outcome[:, :3] * odds[:, :3] - selection[:, :3]
    return pnl.sum(axis=1).reshape((n, -1))

In [ ]:
# Bet action (here, our action is betting 20% of our balance on away team).
selection = (
    np.array([[0, 0, 0.2, 0, 0], [0, 0.7, 0, 0, 0], [0.8, 0, 0.0, 0, 0]]) * 100.0
)

info = fixture.head(3)

# Game odds.
odds = info[
    [
        "preGameOdds1",
        "preGameOddsX",
        "preGameOdds2",
        "preGameAhHome",
        "preGameAhAway",
    ]
].values

# Game result index(homewin -> 0 , draw -> 1, awaywin -> 2).
game_result = info["tgt_outcome"].values.astype(int)
binary_result = np.zeros_like(selection)
np.put_along_axis(binary_result, np.expand_dims(game_result, axis=1), 1, axis=1)

pnl_1X2(selection, binary_result, odds)

array([[-20. ],
       [177.1],
       [-80. ]])

### Asian handicap market

The PnL for the Asian handicap line is more complicated. It is related to the game goal-difference and the actual handicap line. It can result, as we described above, in 5 outcomes: win/half-win/fold/half-loss/loss.

$$ profit_{AH} = \begin{cases} 
     0.0 & \text{If Gd + line = 0} \\\\ 
     \frac{odds -1}{2}& \text{If Gd + line = 0.25}\\\\
     odds -1 & \text{If Gd + line >= 0.5} \\\\
     -0.5 & \text{If Gd + line = -0.25} \\\\
     -1.0 & \text{If Gd + line <= -0.5} \end{cases} $$
 
 With:

+ Gd : game goal difference
+ line: Asian handicap line
+ Odds : Asian handicap odds

In [ ]:
#| export


def pnl_ah(
    selection: np.ndarray,  # The amount invested on each selection; shape n x 5; last 2 are for home/away asian handicap
    odds: np.ndarray,  # market odds in 1|X|2|A1|A2 order; shape n x 5
    obs_gd: np.ndarray,  # Game goal-difference; shape (n,)
    ah_line: np.ndarray,  # Asian line could be integer, half or quarter line; shape (n,)
) -> np.ndarray:  # Asian Handicap PnL.
    "Returns the Asian Handicap PnL"

    # check dimension
    n = selection.shape[0]
    obs_gd = obs_gd.reshape((n, -1))
    ah_line = ah_line.reshape((n, -1))
    assert selection.shape == odds.shape, "odds and selection should be same shape!"

    def _pnl_ah(obs_gd, ah_line, ah_odds):
        "provides the asian outcome given for a unit bet."
        # Team advantage.
        gd_advantage = obs_gd + ah_line

        if gd_advantage == 0:
            return 0.0
        elif gd_advantage == 0.25:
            return (ah_odds - 1) * 0.5
        elif gd_advantage == -0.25:
            return -0.5
        elif gd_advantage >= 0.5:
            return ah_odds - 1
        elif gd_advantage <= -0.5:
            return -1.0

    ah_selection = selection[:, -2:]
    ah_odds = odds[:, -2:]

    # change line sign if betting on away
    ah_idx = np.where(ah_selection > 0)
    flip_sign = np.zeros_like(ah_line)
    flip_sign[ah_idx[0], 0] = np.where(ah_idx[1] == 0, 1, -1)

    # reshape odds
    _ah_odds = np.zeros_like(ah_line)
    _ah_odds[ah_idx[0], 0] = ah_odds[ah_idx]

    # reshape selection
    _ah_sel = np.zeros_like(ah_line)
    _ah_sel[ah_idx[0], 0] = ah_selection[ah_idx]

    _pnl_ah_v = np.vectorize(_pnl_ah)
    _unit_pnl = _pnl_ah_v(
        obs_gd * flip_sign, ah_line * flip_sign, _ah_odds.reshape((n, -1))
    )
    
    return _unit_pnl * _ah_sel.reshape((n, -1))

In [ ]:
selection = (
    np.array([[0, 0, 0.0, 0.0, 0.5], [0, 0, 0, 0, 0], [0, 0, 0.0, 0.2, 0]]) * 100.0
)

info = fixture.head(3)

# Game odds.
odds = info[
    [
        "preGameOdds1",
        "preGameOddsX",
        "preGameOdds2",
        "preGameAhHome",
        "preGameAhAway",
    ]
].values

obs_gd = info.tgt_gd.values
ah_line = info.LineId.values


pnl_ah(selection, odds, obs_gd, ah_line)

array([[ 21.],
       [  0.],
       [-20.]])

## Pnl wrapper

This function computes the total PnL:

In [ ]:
#| export

def pnl(
    selection: np.ndarray,  # The amount invested on each selection; shape n x 5; last 2 are for home/away asian handicap
    odds: np.ndarray,  # market odds in 1|X|2|A1|A2 order; shape n x 5
    obs_gd: np.ndarray,  # Game goal-difference; shape (n,)
    ah_line: np.ndarray,  # Asian line could be integer, half or quarter line; shape (n,)
) -> np.ndarray:  # Asian Handicap PnL.
    "Returns the total PnL"
    # check dimesnion
    n = selection.shape[0]
    assert selection.shape == odds.shape, "odds and selection should be same shape!"

    if len(obs_gd.shape) > 1 and obs_gd.shape[1] == 1:
        obs_gd = obs_gd.squeeze(1)
    binary_result = np.zeros_like(selection)
    binary_result[obs_gd > 0, 0] = 1
    binary_result[obs_gd == 0, 1] = 1
    binary_result[obs_gd < 0, 2] = 1

    # 1x2 pnl
    _pnl_1x2 = pnl_1X2(selection, binary_result, odds)

    # ah-line
    _pnl_ah = pnl_ah(selection, odds, obs_gd, ah_line)
    
    _total_pnl = _pnl_1x2 + _pnl_ah

    return _total_pnl

In [ ]:
selection = (
    np.array(
        [
            [0, 0.0, 0, 0.0, 0.3],  # bet on asian 2
            #[0.3, 0, 0, 0, 0],  # bet on home
            #[0, 0, 0.6, 0.0, 0],  # bet on away
            #[0, 0, 0.0, 0.6, 0],  # bet on asian 1
            #[0, 0.5, 0.0, 0.0, 0],  # bet on X
        ]
    )
    * 100.0
)

info = fixture.head(selection.shape[0])

# Game odds.
odds = info[
    [
        "preGameOdds1",
        "preGameOddsX",
        "preGameOdds2",
        "preGameAhHome",
        "preGameAhAway",
    ]
].values

obs_gd = info.tgt_gd.values
ah_line = info.LineId.values

pnl(selection, odds, obs_gd, ah_line)

array([[12.6]])

In [ ]:
#| hide

import nbdev

nbdev.nbdev_export()